name: appfotajer
description: "تطبيق توصيل طلبات"
publish_to: 'none'
version: 1.3.9+20

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management (اختر واحدة: provider أو bloc)
  provider: ^6.1.2 
  # flutter_bloc: ^9.1.1
  # Images
  image_picker: ^1.1.2 
  flutter_image_compress: ^2.1.0 
  cached_network_image: ^3.3.1 
  # Backend
  appwrite: ^17.1.0 
  
  # ******* إضافة Firebase Core *******
  # أساسية لتهيئة Firebase في التطبيق
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.0
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3 
  # Location & Maps
  geolocator: ^12.0.0 

  permission_handler: ^12.0.1
  # Localization & Formatting
  intl: ^0.20.2 
  flutter_localizations:
    sdk: flutter
  # UI & Utils
  google_fonts: ^6.2.1 
  fluttertoast: ^8.2.5 
  uuid: ^4.4.0 
  font_awesome_flutter: ^10.7.0 
  flutter_local_notifications: ^17.1.2 
  url_launcher: ^6.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.0.2 
  flutter_lints: ^4.0.0 
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_app.png"
  adaptive_icon_background: "assets/images/logo_app_background.png"
  adaptive_icon_foreground: "assets/images/logo_app_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash_logo.png"
  android_12: true